### ISSUE TITLE
Sending emails when creating/closing elections 

### ISSUE THREAD

**Issue by guhur** [MieuxVoter/mvapi#11]
When an election is created, the user should be able to provide email addresses to invite people joining the election. This feature is only activated when the flag "is_opened" is set at false. The user receives as well an email with a special token for closing the election. 

The email addresses are then stored until the election is closed. At that time, each voter receives an email with a link to the results. The email addresses are then deleted.

**Comment by sebsheep** [comment]
Starter of this issue in #12 
I'll open another issue with a todo list to improve this starter.
