### ISSUE TITLE
possibility to send link by mail

### ISSUE THREAD

**Issue by roipoussiere** [MieuxVoter/mvapi#37]
When the election is just created, it can be useful to have the possibility to give an email in order receive the links, preventing the lost of one of them.

**Comment by HermessNRJ** [comment]
Its already done  #28 
Just add the page on the front.

**Comment by roipoussiere** [comment]
So it's fixed but https://app.mieuxvoter.fr/ is not up to date?

**Comment by HermessNRJ** [comment]
No, because the functionality is not yet implemented in the front ...

**Comment by roipoussiere** [comment]
Ok I'm closing this. The related is on the front is here: https://github.com/MieuxVoter/mvfront-react/issues/35
